FROM r-base:3.4.4

COPY ./packages.txt /usr/src/requirements
COPY ./r-packages.txt /usr/src/requirements

WORKDIR /usr/src/requirements

RUN apt-get update && apt-get install -y $(cat packages.txt)

RUN PACKAGES=`cat r-packages.txt` && Rscript -e "install.packages(c($PACKAGES))"


